### ISSUE TITLE
请问android穿山甲「open_ad_sdk」是不是需要手动导入？

### ISSUE THREAD

**Issue by tyf221578** [fengerwoo/flutter_ad#1]
如题

**Comment by fengerwoo** [comment]
不需要，穿山甲、广点通都不需要，直接使用即可，代码参考example工程的 [main.dart ](https://github1s.com/fengerwoo/flutter_ad/blob/main/example/lib/main.dart)

```yaml
dependencies:
    flutter_ad: ^1.3.0
```
然后执行
```shell
flutter pub get
flutter packages get
```

当前本插件1.3.0对应的广告平台版本
穿山甲：3.5.0.3
广点通：4.333.1203

**Comment by tyf221578** [comment]
两个平台都已测试，完美运行，完美回调，非常棒！

**Comment by fengerwoo** [comment]
谢谢你的Star，issues我关闭了哈
