### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by tyf221578** [fengerwoo/flutter_ad#2]
1. 其他的广告形式请问有接入的打算吗？比如Banner广告、插屏广告、信息流广告等。
2. 开屏广告希望能做成自定义形式的，因为app开屏底部会放入产品的Logo和简介内容。

**Comment by fengerwoo** [comment]
目前是根据自己业务需求来开发，因为工作太忙，没有时间去全面完善

1，其他形式广告，后面可能会接入Banner
2，开屏暂时没有修改计划

**Comment by JaredLees** [comment]
+1，用过tencentAd，直接崩溃。希望大佬有空接入下插屏广告、信息流广告。

**Comment by fengerwoo** [comment]
@JaredLees @tyf221578 未来一两周计划接入插屏、Banner广告

**Comment by fengerwoo** [comment]
@tyf221578 @JaredLees 穿山甲Banner广告已接入

**Comment by JaredLees** [comment]
赞




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月5日(星期一) 晚上9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fengerwoo/flutter_ad] 几点建议 (#2)





 
@tyf221578 @JaredLees 穿山甲Banner广告已接入

**Comment by tyf221578** [comment]
赞

**Comment by yy1300326388** [comment]
@tyf221578 @JaredLees 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
