### ISSUE TITLE
请问能不能单独拆一个只有腾讯广点通的版本？

### ISSUE THREAD

**Issue by tyf221578** [fengerwoo/flutter_ad#3]
已上线的产品之前集成了穿山甲，如果再集成本库的话，穿山甲的代码就重复了，导致程序无法运行了，并且之前的代码位要全部重写，所以能否拆一个只有广点通的版本出来呢？

**Comment by tyf221578** [comment]
我自己clone下来把穿山甲的内容删除后就可以用了。
另外再确认下，为什么直接使用demo中的腾讯优量汇的appid和激励视频id可以播放，换成我自己的就报错，请问知道什么原因吗？
`{code: 0, data: {code: 5010, message: 广告样式校验失败，请检查广告位与接口使用是否一致}, message: onError@错误：code:5010 message:广告样式校验失败，请检查广告位与接口使用是否一致}`

下图是在腾讯优量汇的广告位截图
<img width="1292" alt="WX20210412-202448@2x" src="https://user-images.githubusercontent.com/1350800/114394041-544f0d80-9bcd-11eb-88b2-9dd4ac2f3ce9.png">

**Comment by tyf221578** [comment]
自己回答下把！找了很久原因终于找到了。
使用该库，广点通的激励视频的「选择广告样式」只能选择「SDK原生渲染」，否则会报我上面一条的错误。
在广点通后台添加激励广告的时候默认是选中「平台模版渲染2.0」的，这种方式无法渲染，注意、注意、注意～

**Comment by yy1300326388** [comment]
@tyf221578 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
