### ISSUE TITLE
Exception has occurred.

### ISSUE THREAD

**Issue by YelenaLemon** [fengerwoo/flutter_ad#4]
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method showSplashAD on channel flutter_ad/csj))

**Comment by fengerwoo** [comment]
引入依赖库，flutter pub package get 后也是这样？有详细报错吗

**Comment by YelenaLemon** [comment]
这个就是最详细的了我下载你的demo，和新建项目，初始化均不成功。你跟原生的通道没有做好衔接吧。

**Comment by fengerwoo** [comment]
Flutter版本多少，切换成2.0.2试试

**Comment by fengerwoo** [comment]
你是用的iOS端吧，暂时只支持Android 哈

**Comment by YelenaLemon** [comment]
好的



发自我的iPhone


------------------ Original ------------------
From: fenger ***@***.***&gt;
Date: Thu,Jun 10,2021 11:12 AM
To: fengerwoo/flutter_ad ***@***.***&gt;
Cc: YelenaLemon ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fengerwoo/flutter_ad] Exception has occurred. (#4)





 
你是用的iOS端吧，暂时只支持Android 哈

**Comment by yy1300326388** [comment]
@YelenaLemon 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
