### ISSUE TITLE
广点通iOS端报错

### ISSUE THREAD

**Issue by tjclovesym** [fengerwoo/flutter_ad#5]
iOS初始化广点通和播放开屏广告都报错MissingPluginException (MissingPluginException(No implementation found for method init on channel flutter_ad/gdt))。安卓端可以正常运行

**Comment by fengerwoo** [comment]
暂不支持iOS端哈

**Comment by yy1300326388** [comment]
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
