### ISSUE TITLE
支持ios吗？

### ISSUE THREAD

**Issue by Mockingbird1234** [fengerwoo/flutter_ad#6]
请问支持ios吗？

**Comment by fengerwoo** [comment]
暂时不支持

**Comment by yy1300326388** [comment]
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
